repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: check-yaml
# -   repo: https://github.com/ansible/ansible-lint.git
#     rev: v4.1.0
#     hooks:
#       - id: ansible-lint
#         files: \.(yaml|yml)$