repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: check-yaml
- repo: local
  hooks:
  - id: ansible-lint
    name: Ansible-lint
    description: This hook runs ansible-lint.
    entry: ansible-lint --force-color .
    language: python
    # do not pass files to ansible-lint, see:
    # https://github.com/ansible/ansible-lint/issues/611
    pass_filenames: false
    always_run: true