- name: Install remi repo.
  yum:
    name: "{{ remi_repo_url }}"
    state: present

- name: Import remi GPG key.
  rpm_key:
    key: "{{ remi_repo_gpg_key_url }}"
    state: present

- name: Enable remi repo for PHP 7.3.
  set_fact:
    php_enablerepo: "remi,remi-php73"
  when: php_version == "7.3"

- name: Ensure PHP packages are installed.
  package:
    name: "{{ php_packages }}"
    state: "{{ php_packages_state }}"
    enablerepo: "{{ php_enablerepo | default(omit, true) }}"
  notify: restart httpd

- name: Changing upload size PHP
  lineinfile:
    dest: /etc/php.ini
    regexp: "upload_max_filesize ="
    line: "upload_max_filesize = 50M"
    backup: yes
  notify: restart httpd

- name: Changing upload size PHP
  lineinfile:
    dest: /etc/php.ini
    regexp: "post_max_size ="
    line: "post_max_size = 50M"
  notify: restart httpd


- name: installing phpmyadmin
  yum:
    name: "phpmyadmin"
    state: "present"
    enablerepo: "{{ phpmyadmin_enablerepo }}"
  notify: restart httpd

- name: copying config file for phpmyadmin
  template:
    src: phpmyadmin.config.j2
    dest: /etc/httpd/conf.d/phpMyAdmin.conf
    force: no
  notify: restart httpd

- name: Check if Composer is installed.
  stat: "path={{ composer_path }}"
  register: composer_bin
  tags: composer

- name: Get Composer installer signature.
  uri:
    url: https://composer.github.io/installer.sig
    return_content: true
  register: composer_installer_signature
  when: not composer_bin.stat.exists

- name: Download Composer installer.
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755
    checksum: "sha384:{{ composer_installer_signature.content }}"
  when: not composer_bin.stat.exists

- name: Run Composer installer.
  command: >
    php /tmp/composer-installer.php --install-dir=/usr/local/bin --filename=composer
  when: not composer_bin.stat.exists
