- name: Installing php and commond modules
  apt:
    name:
      - php
      - libapache2-mod-php
      - php-cli
      - php-common
      - php-curl
      - php-gd
      - php-imap
      - php-mbstring
      - php-pdo
      - php-mysql
      - php-fileinfo
      - php-zip
      - php-intl
      - php-bcmath
      - php-xml
    state: present
  notify: restart apache2

- name: get php version of box
  shell: |
    set -o pipefail
    php --version | head -n 1 | cut -c 5-7
  args:
    executable: /bin/bash
  register: php_version
  changed_when: false

- name: Changing upload size PHP
  lineinfile:
    dest: /etc/php/{{ php_version.stdout }}/apache2/php.ini
    regexp: "upload_max_filesize ="
    line: "upload_max_filesize = 50M"
    backup: yes
  notify: restart apache2

- name: Changing post max size PHP
  lineinfile:
    dest: /etc/php/{{ php_version.stdout }}/apache2/php.ini
    regexp: "post_max_size ="
    line: "post_max_size = 50M"
  notify: restart apache2

- name: Check if Composer is installed.
  stat: "path={{ composer_path }}"
  register: composer_bin
  tags: composer

- name: Get Composer installer signature.
  uri:
    url: https://composer.github.io/installer.sig
    return_content: true
  register: composer_installer_signature
  when: not composer_bin.stat.exists

- name: Download Composer installer.
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755
    checksum: "sha384:{{ composer_installer_signature.content }}"
  when: not composer_bin.stat.exists

- name: Run Composer installer.
  command: >
    php /tmp/composer-installer.php --install-dir=/usr/local/bin --filename=composer
  when: not composer_bin.stat.exists
  changed_when: false

- name: Ensure phpMyAdmin is installed.
  apt:
    name: phpmyadmin
    state: present
  notify: restart apache2

- name: Ensure phpMyAdmin config file is included in Apache config.
  lineinfile:
    dest: /etc/apache2/apache2.conf
    state: present
    regexp: "^Include.+phpmyadmin.+$"
    line: "Include /etc/phpmyadmin/apache.conf"
    insertafter: "EOF"
  notify: restart apache2